@startuml OOP Lab5
title OOP Lab5

class Bank
{
	- bank_name : String
	- user_list : List~User~
	- atm_list : List~ATM~
	+ add_user(user: User) : void
	+ add_atm_machine(atm: ATMMachine) : void
	+ add_edc_machine(edc: EDCMachine) : void
	+ add_counter(counter: Counter) : void
	+ get_atm_by_id(atm_id: String) : ATMMachine
	+ get_edc_by_id(edc_id: String) : EDCMachine
	+ get_counter_by_id(counter_id: String) : Counter
	+ search_account_from_card(card_no: String) : Account
}

class User
{
	- user_id : String
	- name : String
	- acc_list : List~Account~
	- counter_list : List~Counter~
	- edc_list : List~EDC~
	+ add_account(account: Account) : void
	+ search_account_from_card(card_no : String) : Account
	+ get_all_account() : List~Account~
}

class Card
{
	- card_no : String
	- acc_id : String
	- pin : String
	- fees : Float
	+ validate_pin(pin : String) : bool
	+ get_card_type() : String
}

class Account
{
	- acc_id : String
	- balance : Float
	- atm_card : Card
	- transaction_list : List~Transaction~
	- user : ~User~
	- interest_rate : Float
	- daily_limit : Float
	+ deposit(atm: ATM, amount: Float) : void
	+ withdraw(atm: ATM, amount: Float) : void
	+ transfer(atm: ATM, amount: Float, target: Account) : void
	+ add_atm_card(atm_card: Card) : void
	+ print_transactions() : void
}

class Transaction
{
	- type : String
	- channel_type : String
	- channel_id : String
	- atm_id : String
	- amount : Float
	- balance : Float
	- [target_acc_id] : String
}

class SavingAccount
{

}

class FixedAccount
{

}

class CurrentAccount
{

}

class ATMCard
{

}

class DebitCard
{

}

class Channel
{

}

class ATMMachine
{
	- atm_id : String
	- money : Float
	- bank : ~Bank~
	+ insert_card(atm_card: ATMCard, pin: String) : Bool
}

class Counter
{

}

class EDCMachine
{

}

' Bank
Bank "1" o-- "*" User : contains
Bank "1" <--> "*" ATMMachine : contains
Bank "1" <--> "*" Counter : contains
Bank "1" <--> "*" EDCMachine : contains
' Account
Account "1" <--> "1" User : has
Account "1" --> "1" Card : has
Account "1" o-- "*" Transaction : records
' Account type
Account <|-- SavingAccount
Account <|-- FixedAccount
Account <|-- CurrentAccount
' Card type
Card <|-- ATMCard
Card <|-- DebitCard
' Channel type
Channel <|-- ATMMachine
Channel <|-- Counter
Channel <|-- EDCMachine
@enduml