@startuml UsecaseSequenceDiagram

actor Customer as A_Customer

participant GameStore
participant Customer as P_Customer
participant Room
participant Reservation
participant Logs

A_Customer -> GameStore : Create booking (customerId, roomId, start_time, end_time)
activate A_Customer
activate GameStore

alt booking success

	loop get customer by id

		GameStore -> P_Customer: Get customer
		activate P_Customer

		P_Customer -> GameStore : Customer
		deactivate P_Customer

	end

	GameStore -> P_Customer : check_time_availability(start_time, end_time)
	activate P_Customer

	P_Customer -> GameStore : Success
	deactivate P_Customer

	loop get room by id

		GameStore -> Room : Get room
		activate Room

		Room -> GameStore : Room
		deactivate Room

	end

	GameStore -> Room : Set booking
	activate Room

	Room -> Reservation : Create Reservation(customer)
	activate Reservation
	Reservation -> Reservation : status = Pending
	Reservation -> Room : Reservation
	deactivate Reservation

	Room -> GameStore : Reservation
	deactivate Room

	GameStore -> P_Customer : addReservation(reservation)
	activate P_Customer
	P_Customer -> GameStore : Success
	deactivate P_Customer

	GameStore -> Logs : Create Logs(customer, reservation)
	activate Logs
	Logs -> Logs : action=Create Reservation
	Logs -> GameStore : Logs
	deactivate Logs

	GameStore -> A_Customer : Success

else booking fail (fail to get customer)

	P_Customer -> GameStore : Fail (fail to get customer)
	GameStore -> A_Customer : Fail (fail to get customer)

else booking fail (fail customer invalid time frame)

	P_Customer -> GameStore : Fail (fail customer invalid time frame)
	
	GameStore -> A_Customer : Fail (fail customer invalid time frame)

else booking fail (fail to get rooms)

	Room -> GameStore : Fail (fail to get rooms)
	GameStore -> A_Customer : Fail (fail to get rooms)

else booking fail (fail to create reservation room invalid time frame)

	Room -> GameStore : Fail (fail to create reservation room invalid time frame)
	GameStore -> A_Customer : Fail (fail to create reservation room invalid time frame)

else booking fail (fail to add reservation)

	P_Customer -> GameStore : Fail (fail to add reservation)

	GameStore -> A_Customer : Fail (fail to add reservation)

	deactivate GameStore
	deactivate A_Customer

end

@enduml
