@startuml UsecaseSequenceDiagram

actor Customer

Customer -> GameStore : Create booking (roomId)
activate Customer
activate GameStore

alt booking success

	loop get room by id

		GameStore -> Room : Get room
		activate Room

		Room -> GameStore : Room
		deactivate Room

	end

	GameStore -> Room : Set booking
	activate Room

	Room -> Reservation : Create Reservation(customer, room, room_type)
	activate Reservation
	Reservation -> Reservation : status = Pending
	Reservation -> Room : Created(reservation_id)
	deactivate Reservation

	Room -> GameStore : Reservation
	deactivate Room

	GameStore -> Logs : Create Logs(customer, reservation)
	activate Logs
	Logs -> Logs : action=Create Reservation
	Logs -> GameStore : Logs
	deactivate Logs

	GameStore -> Customer : Success

else booking fail (fail to get rooms)

	Room -> GameStore : Fail (fail to get rooms)
	GameStore -> Customer : Fail (fail to get rooms)

else booking fail (fail to create reservation)

	Room -> GameStore : Fail (fail to create reservation)
	GameStore -> Customer : Fail (fail to create reservation)

	deactivate GameStore
	deactivate Customer

end

@enduml
