@startuml UsecaseSequenceDiagram

actor Customer

Customer -> GameStore : Get available Room
activate Customer
activate GameStore

alt Have available rooms

	GameStore -> Room : Get available Room
	activate Room

	loop
		Room -> Room : is_available()
	end

	Room -> GameStore : All available rooms
	deactivate Room

	GameStore -> Customer : All available rooms

else No available rooms

	Room -> GameStore : No available rooms
	GameStore -> Customer : No available rooms
	deactivate GameStore
	deactivate Customer

end

Customer -> GameStore : Create booking (Room ID)
activate Customer
activate GameStore

alt booking success

	loop get room by id

		GameStore -> Room : Get room
		activate Room

		Room -> GameStore : Room
		deactivate Room

	end

	GameStore -> Room : Set booking
	activate Room

	Room -> Reservation : Create Reservation(customer, room, room_type)
	activate Reservation
	Reservation -> Reservation : status = Pending
	Reservation -> Room : Created(reservation_id)
	deactivate Reservation

	Room -> GameStore : Reservation
	deactivate Room

	GameStore -> Transaction : Create Transaction(reservation_id)
	activate Transaction
	Transaction -> Transaction : status = Pending
	Transaction -> GameStore : Transaction Instance
	deactivate Transaction

	GameStore -> Customer : Success

else booking fail (fail to get rooms)

	Room -> GameStore : Fail (fail to get rooms)
	GameStore -> Customer : Fail (fail to get rooms)

else booking fail (fail to create reservation)

	Room -> GameStore : Fail (fail to create reservation)
	GameStore -> Customer : Fail (fail to create reservation)

	deactivate GameStore
	deactivate Customer

end

Customer -> GameStore : Start Payment
activate Customer
activate GameStore

alt payment success

	GameStore -> Payment : Start Payment
	activate Payment
	Payment -> GameStore : Success
	deactivate Payment

	GameStore -> Reservation : Update Reservation (Set status Paid)
	activate Reservation
	Reservation -> Reservation : status = Paid
	Reservation -> GameStore : Updated
	deactivate Reservation

	GameStore -> Transaction : Update Transaction (Set status Success)
	activate Transaction
	Transaction -> Transaction : status = Success
	Transaction -> GameStore : Updated
	deactivate Transaction

	GameStore -> Customer : Success

else payment fail

	Payment -> GameStore : Fail

	GameStore -> Reservation : Update Reservation (Set status Cancel)
	activate Reservation
	Reservation -> Reservation : status = Cancel
	Reservation -> GameStore : Updated
	deactivate Reservation

	GameStore -> Transaction : Update Transaction (Set status Fail)
	activate Transaction
	Transaction -> Transaction : status = Success
	Transaction -> GameStore : Updated
	deactivate Transaction

	GameStore -> Customer : Fail

	deactivate GameStore
	deactivate Customer

end

@enduml
